# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - employee_management_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL}
    depends_on:
      - mongo

  employee-management-server:
      image: ralph28/employee-management-server:latest
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - mongo
      environment:
        SPRING_DATA_MONGODB_URI: ${MONGO_URL}

#  employee-management-client:
#     image: ralph28/employee-management-client:latest
#     restart: always
#     ports:
#       - "80:80"
#     depends_on:
#       - employee-management-serveremployee-management-client:
#     image: ralph28/employee-management-client:latest
#     restart: always
#     ports:
#       - "80:80"
#     depends_on:
#       - employee-management-server

volumes:
  employee_management_data:
